.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH XFCE4-SENSORS 1 2017
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
Xfce 4 Sensors \- sensors viewer for Xfce 4
.SH SYNOPSIS
.B xfce4-sensors
.RI [ option ]
.br
.SH DESCRIPTION
.B xfce4-sensors
is a sensors viewer for the Xfce 4 project and the sensors panel plugin.
.SH OPTIONS
.TP
\-h, --help
display a short help text
.TP
\-l, --license
print license information
.TP
\-V, --version
print version information
.SH AUTHOR
Fabian Nowak <timystery@arcor.de>.
.PP
This manual page was written by Fabian Nowak <timystery@arcor.de>.
